version: '2'
services:
    eztour-app:
        image: eztour
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://eztour-postgresql:5432/eztour
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eztour-postgresql:
        extends:
            file: postgresql.yml
            service: eztour-postgresql
